services:
  app:
    image: bi-app    # docker build -t app .
    container_name: app
    build: .
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://cufibr8gph6c73849nkg-a.oregon-postgres.render.com:5432/bi_db_wt7o?ssl=true&sslmode=require
      SPRING_DATASOURCE_USERNAME: bi_db_wt7o_userr
      SPRING_DATASOURCE_PASSWORD: eeMclx3H92H2JXQdvY0Ph1ytcsUAERNO
    restart: on-failure