services:
  app:
    image: bi-app    # docker build -t app .
    container_name: app
    build: .
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://root:naVlqMmhncvapgmqtAsTwdtseErNQJOF@junction.proxy.rlwy.net:42993/railway
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: naVlqMmhncvapgmqtAsTwdtseErNQJOF
    restart: on-failure