services:
  app:
    image: bi-app    # docker build -t app .
    container_name: app
    build: .
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-ctroh0tumphs73ffki10-a.oregon-postgres.render.com:5432/bi_database_g8ft?ssl=true&sslmode=require
      SPRING_DATASOURCE_USERNAME: bi_database_g8ft_user
      SPRING_DATASOURCE_PASSWORD: sZOy8LtaaxZFjaKZW2rqaMJAuqvevBVm
    restart: on-failure